/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        emWin Font Converter (ST) version 5.44                      *
*        Compiled Nov 10 2017, 08:53:23                              *
*                                                                    *
*        (c) 1998 - 2017 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: Microsoft JhengHei UI20.c                             *
* Font:        Microsoft JhengHei UI                                 *
* Height:      20                                                    *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height:  20                                           *
* Range disabled:       0000 - FFFF                                  *
* Read pattern file: C:\Users\Lenovo\Desktop\¾ºÈü\µçÈü\×Ö¿â.txt      *
*                                                                    *
**********************************************************************
*/

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font.
*/
extern GUI_CONST_STORAGE GUI_FONT GUI_FontMicrosoftJhengHeiUI20;

/* Start of unicode area <Basic Latin> */
GUI_CONST_STORAGE unsigned char acGUI_FontMicrosoftJhengHeiUI20_0028[ 20] = { /* code 0028, LEFT PARENTHESIS */
  ________,
  ________,
  ________,
  ________,
  ____XX__,
  ___XX___,
  __XX____,
  __XX____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  __XX____,
  __XX____,
  ___XX___,
  ____XX__,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontMicrosoftJhengHeiUI20_0029[ 20] = { /* code 0029, RIGHT PARENTHESIS */
  ________,
  ________,
  ________,
  ________,
  XX______,
  _XX_____,
  __XX____,
  __XX____,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  __XX____,
  __XX____,
  _XX_____,
  XX______,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontMicrosoftJhengHeiUI20_002E[ 20] = { /* code 002E, FULL STOP */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  _XX_____,
  _XX_____,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontMicrosoftJhengHeiUI20_002F[ 20] = { /* code 002F, SOLIDUS */
  ________,
  ________,
  ________,
  ________,
  _____XX_,
  _____XX_,
  ____XX__,
  ____XX__,
  ___XX___,
  ___XX___,
  ___X____,
  __XX____,
  __X_____,
  __X_____,
  _X______,
  _X______,
  X_______,
  X_______,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontMicrosoftJhengHeiUI20_0030[ 40] = { /* code 0030, DIGIT ZERO */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ___XXXX_,________,
  __XX__XX,________,
  __X____X,X_______,
  _XX____X,X_______,
  _XX____X,X_______,
  _XX____X,X_______,
  _XX____X,X_______,
  _XX____X,X_______,
  _XX____X,X_______,
  _XX____X,________,
  __XX__XX,________,
  ___XXXX_,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontMicrosoftJhengHeiUI20_0031[ 40] = { /* code 0031, DIGIT ONE */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  _____XX_,________,
  ____XXX_,________,
  ___XXXX_,________,
  __X__XX_,________,
  _____XX_,________,
  _____XX_,________,
  _____XX_,________,
  _____XX_,________,
  _____XX_,________,
  _____XX_,________,
  _____XX_,________,
  _____XX_,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontMicrosoftJhengHeiUI20_0032[ 40] = { /* code 0032, DIGIT TWO */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  __XXXXX_,________,
  __X___XX,X_______,
  _______X,X_______,
  _______X,X_______,
  _______X,X_______,
  ______XX,________,
  _____XXX,________,
  ___XXX__,________,
  __XXX___,________,
  _XXX____,________,
  _XX_____,________,
  _XXXXXXX,X_______,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontMicrosoftJhengHeiUI20_0033[ 40] = { /* code 0033, DIGIT THREE */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  _XXXXXX_,________,
  _X___XXX,________,
  ______XX,________,
  ______XX,________,
  _____XX_,________,
  __XXXX__,________,
  _____XX_,________,
  ______XX,________,
  ______XX,________,
  ______XX,________,
  _X___XX_,________,
  _XXXXX__,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontMicrosoftJhengHeiUI20_0034[ 40] = { /* code 0034, DIGIT FOUR */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ______XX,________,
  _____XXX,________,
  ____XXXX,________,
  ____X_XX,________,
  ___X__XX,________,
  __XX__XX,________,
  _XX___XX,________,
  XX____XX,________,
  XXXXXXXX,XX______,
  ______XX,________,
  ______XX,________,
  ______XX,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontMicrosoftJhengHeiUI20_0035[ 40] = { /* code 0035, DIGIT FIVE */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  __XXXXXX,X_______,
  __XX____,________,
  __XX____,________,
  __XX____,________,
  __XX____,________,
  __XXXXX_,________,
  ______XX,X_______,
  _______X,X_______,
  _______X,X_______,
  _______X,X_______,
  ______XX,________,
  _XXXXXX_,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontMicrosoftJhengHeiUI20_0036[ 40] = { /* code 0036, DIGIT SIX */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ____XXXX,________,
  ___XX___,________,
  __XX____,________,
  _XX_____,________,
  _XX_____,________,
  _XX_XXXX,________,
  _XXX__XX,X_______,
  _XX____X,X_______,
  _XX____X,X_______,
  _XX____X,X_______,
  __XX__XX,________,
  ___XXXX_,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontMicrosoftJhengHeiUI20_0037[ 40] = { /* code 0037, DIGIT SEVEN */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  _XXXXXXX,X_______,
  _______X,X_______,
  ______XX,________,
  ______XX,________,
  _____XX_,________,
  _____XX_,________,
  _____X__,________,
  ____XX__,________,
  ____XX__,________,
  ____X___,________,
  ___XX___,________,
  ___XX___,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontMicrosoftJhengHeiUI20_0038[ 40] = { /* code 0038, DIGIT EIGHT */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ___XXXX_,________,
  _XXX__XX,X_______,
  _XX____X,X_______,
  _XX____X,X_______,
  __XX__XX,________,
  ____XXX_,________,
  __XX__XX,________,
  _XX____X,X_______,
  _XX____X,X_______,
  _XX____X,X_______,
  __XX__XX,________,
  ___XXXX_,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontMicrosoftJhengHeiUI20_0039[ 40] = { /* code 0039, DIGIT NINE */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ___XXXX_,________,
  __XX__XX,________,
  _XX____X,X_______,
  _XX____X,X_______,
  _XX____X,X_______,
  __XX__XX,X_______,
  ___XXXXX,X_______,
  _______X,X_______,
  _______X,X_______,
  ______XX,________,
  __X___XX,________,
  __XXXX__,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontMicrosoftJhengHeiUI20_003A[ 20] = { /* code 003A, COLON */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  _XX_____,
  _XX_____,
  ________,
  ________,
  ________,
  ________,
  ________,
  _XX_____,
  _XX_____,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontMicrosoftJhengHeiUI20_0046[ 40] = { /* code 0046, LATIN CAPITAL LETTER F */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  __XXXXXX,________,
  __XX____,________,
  __XX____,________,
  __XX____,________,
  __XX____,________,
  __XXXXXX,________,
  __XX____,________,
  __XX____,________,
  __XX____,________,
  __XX____,________,
  __XX____,________,
  __XX____,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontMicrosoftJhengHeiUI20_004B[ 40] = { /* code 004B, LATIN CAPITAL LETTER K */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  __XX____,XX______,
  __XX___X,X_______,
  __XX__XX,________,
  __XX_XXX,________,
  __XX_XX_,________,
  __XXXX__,________,
  __XXXXX_,________,
  __XX_XX_,________,
  __XX__XX,________,
  __XX___X,X_______,
  __XX___X,XX______,
  __XX____,XX______,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontMicrosoftJhengHeiUI20_0063[ 20] = { /* code 0063, LATIN SMALL LETTER C */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ___XXXXX,
  __XX___X,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  __XX___X,
  ___XXXXX,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontMicrosoftJhengHeiUI20_006D[ 40] = { /* code 006D, LATIN SMALL LETTER M */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  _XX_XXXX,_XXXX___,
  _XXX__XX,XX__XX__,
  _XX____X,X___XX__,
  _XX____X,X___XX__,
  _XX____X,X___XX__,
  _XX____X,X___XX__,
  _XX____X,X___XX__,
  _XX____X,X___XX__,
  _XX____X,X___XX__,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontMicrosoftJhengHeiUI20_006E[ 40] = { /* code 006E, LATIN SMALL LETTER N */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  _XX_XXXX,________,
  _XXX__XX,X_______,
  _XX____X,X_______,
  _XX____X,X_______,
  _XX____X,X_______,
  _XX____X,X_______,
  _XX____X,X_______,
  _XX____X,X_______,
  _XX____X,X_______,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontMicrosoftJhengHeiUI20_0070[ 40] = { /* code 0070, LATIN SMALL LETTER P */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  _XX_XXX_,________,
  _XXX__XX,________,
  _XX____X,X_______,
  _XX____X,X_______,
  _XX____X,X_______,
  _XX____X,X_______,
  _XX____X,X_______,
  _XXX__XX,________,
  _XXXXXX_,________,
  _XX_____,________,
  _XX_____,________,
  _XX_____,________,
  _XX_____,________};

/* Start of unicode area <Basic Greek> */
GUI_CONST_STORAGE unsigned char acGUI_FontMicrosoftJhengHeiUI20_03A9[ 40] = { /* code 03A9, GREEK CAPITAL LETTER OMEGA */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ____XXXX,X_______,
  ___XX___,XX______,
  __XX____,_XX_____,
  _XX_____,__XX____,
  _XX_____,__XX____,
  _XX_____,__XX____,
  _XX_____,__XX____,
  _XX_____,__XX____,
  __XX____,_XX_____,
  __XX____,_XX_____,
  ___XX___,XX______,
  _XXXXX_X,XXXX____,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

/* Start of unicode area <CJK Symbols and Punctuation> */
GUI_CONST_STORAGE unsigned char acGUI_FontMicrosoftJhengHeiUI20_3001[ 40] = { /* code 3001, IDEOGRAPHIC COMMA */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  _______X,________,
  _______X,X_______,
  ________,XX______,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

/* Start of unicode area <CJK Unified Ideographs> */
GUI_CONST_STORAGE unsigned char acGUI_FontMicrosoftJhengHeiUI20_4E0E[ 40] = { /* code 4E0E */
  ________,________,
  ________,________,
  ________,________,
  ___X____,________,
  ___X____,________,
  ___XXXXX,XXXXXX__,
  ___X____,________,
  ___X____,________,
  ___XXXXX,XXXXXXX_,
  ________,_____XX_,
  ________,_____XX_,
  ________,_____XX_,
  _XXXXXXX,XXXX_X__,
  ________,_____X__,
  ________,_____X__,
  ________,_XXXX___,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontMicrosoftJhengHeiUI20_4F5C[ 40] = { /* code 4F5C */
  ________,________,
  ________,________,
  ________,________,
  ____XX__,X_______,
  ____X__X,X_______,
  ___XX__X,XXXXXXX_,
  ___X__XX,_X______,
  __XX__X_,_X______,
  _XXX_XX_,_XXXXXX_,
  _X_X_X__,_X______,
  ___X____,_X______,
  ___X____,_X______,
  ___X____,_XXXXXX_,
  ___X____,_X______,
  ___X____,_X______,
  ___X____,_X______,
  ___X____,_X______,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontMicrosoftJhengHeiUI20_4FDD[ 40] = { /* code 4FDD */
  ________,________,
  ________,________,
  ____X___,________,
  ___XX_XX,XXXXXX__,
  ___X__X_,_____X__,
  ___X__X_,_____X__,
  __XX__X_,_____X__,
  __XX__XX,XXXXXX__,
  _XXX____,_XX_____,
  _X_X____,_XX_____,
  ___X_XXX,XXXXXXX_,
  ___X____,_XX_____,
  ___X___X,_XX_X___,
  ___X__XX,_XXXXX__,
  ___X__X_,_XX__X__,
  ___X_XX_,_XX__XX_,
  ___X_X__,_XX___X_,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontMicrosoftJhengHeiUI20_53C2[ 40] = { /* code 53C2 */
  ________,________,
  ________,________,
  ______X_,________,
  _____XX_,__X_____,
  ___XXX__,___X____,
  ___XXXXX,XXXXX___,
  ______XX,____X___,
  _XXXXXXX,XXXXXXX_,
  ____XX__,__XX____,
  ___XX___,X__XX___,
  __XX___X,X___XX__,
  _XX__XX_,__X___X_,
  ___XX___,XX__X___,
  ______XX,X__XX___,
  ___XXX__,_XX_____,
  ______XX,X_______,
  ___XXX__,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontMicrosoftJhengHeiUI20_540C[ 40] = { /* code 540C */
  ________,________,
  ________,________,
  ________,________,
  __XXXXXX,XXXXXXX_,
  __X_____,_____XX_,
  __X_____,_____XX_,
  __X_XXXX,XXXX_XX_,
  __X_____,_____XX_,
  __X_____,_____XX_,
  __X__XXX,XXX__XX_,
  __X__X__,__X__XX_,
  __X__X__,__X__XX_,
  __X__X__,__X__XX_,
  __X__XXX,XXX__XX_,
  __X_____,_____XX_,
  __X_____,_____XX_,
  __X_____,__XXXX__,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontMicrosoftJhengHeiUI20_5728[ 40] = { /* code 5728 */
  ________,________,
  ________,________,
  ________,________,
  _______X,________,
  ______XX,________,
  _XXXXXXX,XXXXXXX_,
  _____X__,________,
  ____XX__,_X______,
  ___XX___,_X______,
  ___XX___,_X______,
  __XXX_XX,XXXXXX__,
  _XXXX___,_X______,
  ___XX___,_X______,
  ___XX___,_X______,
  ___XX___,_X______,
  ___XX___,_X______,
  ___XXXXX,XXXXXXX_,
  ___XX___,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontMicrosoftJhengHeiUI20_578B[ 40] = { /* code 578B */
  ________,________,
  ________,________,
  ________,________,
  __XXXXXX,X_XX_XX_,
  ___XX_XX,__XX_XX_,
  ___XX_XX,__XX_XX_,
  ___XX_XX,__XX_XX_,
  _XXXXXXX,XXXX_XX_,
  ___XX_XX,__XX_XX_,
  ___X__XX,__XX_XX_,
  __XX__XX,_____XX_,
  __X_____,___XXX__,
  _______X,X_______,
  __XXXXXX,XXXXXX__,
  _______X,X_______,
  _______X,X_______,
  _XXXXXXX,XXXXXXX_,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontMicrosoftJhengHeiUI20_5907[ 40] = { /* code 5907 */
  ________,________,
  ________,________,
  ________,________,
  _____XX_,________,
  ____XXXX,XXXXX___,
  ___XXX__,__XX____,
  __X__XXX,_XX_____,
  _______X,XX______,
  _____XXX,XXX_____,
  ___XXX__,__XXX___,
  _XXXXXXX,XXXXXXX_,
  ___XX__X,X___X___,
  ___XX__X,X___X___,
  ___XXXXX,XXXXX___,
  ___XX__X,X___X___,
  ___XXXXX,XXXXX___,
  ___XX___,____X___,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontMicrosoftJhengHeiUI20_5BB9[ 40] = { /* code 5BB9 */
  ________,________,
  ________,________,
  ________,________,
  _______X,X_______,
  _XXXXXXX,XXXXXXX_,
  _XX_____,_____XX_,
  _XX__XX_,_XX__XX_,
  ____XX__,__XX____,
  ___XX__X,X___XX__,
  __X___XX,XX___X__,
  _____XX_,_XX_____,
  ___XX___,___XX___,
  _XXXXXXX,XXXXXXX_,
  ___X____,____X___,
  ___X____,____X___,
  ___XXXXX,XXXXX___,
  ___X____,____X___,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontMicrosoftJhengHeiUI20_5C31[ 40] = { /* code 5C31 */
  ________,________,
  ________,________,
  ____X___,__XX____,
  ____XX__,__XX_X__,
  _XXXXXXX,__XXXX__,
  ________,__XX____,
  __XXXXXX,XXXXXXX_,
  __X___XX,__XX____,
  __X___XX,__X_____,
  __XXXXXX,__X_X___,
  ____X___,__X_X___,
  __XXX_X_,_XX_X___,
  __X_X_XX,_XX_X___,
  __X_X__X,_X__X_X_,
  _XX_X__X,XX__X_X_,
  _X__X___,X___X_X_,
  ___XX___,X___XXX_,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontMicrosoftJhengHeiUI20_5DE5[ 40] = { /* code 5DE5 */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  __XXXXXX,XXXXXX__,
  _______X,X_______,
  _______X,X_______,
  _______X,X_______,
  _______X,X_______,
  _______X,X_______,
  _______X,X_______,
  _______X,X_______,
  _______X,X_______,
  _______X,X_______,
  _______X,X_______,
  _______X,X_______,
  _XXXXXXX,XXXXXXX_,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontMicrosoftJhengHeiUI20_5EA6[ 40] = { /* code 5EA6 */
  ________,________,
  ________,________,
  ________,________,
  _______X,X_______,
  __XXXXXX,XXXXXXX_,
  __XX____,________,
  __XX__XX,___XX___,
  __XXXXXX,XXXXXXX_,
  __XX__XX,___XX___,
  __XX__XX,XXXXX___,
  __XX____,________,
  __XX_XXX,XXXXX___,
  __XX__XX,___XX___,
  __XX___X,__XX____,
  __X____X,XXX_____,
  _XX___XX,X_XX____,
  _XX_XX__,____XXX_,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontMicrosoftJhengHeiUI20_5F00[ 40] = { /* code 5F00 */
  ________,________,
  ________,________,
  ________,________,
  __XXXXXX,XXXXXXX_,
  ____XX__,__XX____,
  ____XX__,__XX____,
  ____XX__,__XX____,
  ____XX__,__XX____,
  ____XX__,__XX____,
  _XXXXXXX,XXXXXXX_,
  ____XX__,__XX____,
  ____XX__,__XX____,
  ____X___,__XX____,
  ___XX___,__XX____,
  ___X____,__XX____,
  __XX____,__XX____,
  __X_____,__XX____,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontMicrosoftJhengHeiUI20_5FD9[ 40] = { /* code 5FD9 */
  ________,________,
  ________,________,
  ________,________,
  ___XX___,_XX_____,
  ___XX___,_XX_____,
  ___XX___,__XX____,
  __XXX_XX,XXXXXXX_,
  _XXXXX_X,X_______,
  _XXXXX_X,X_______,
  _X_XX_XX,X_______,
  _X_XX__X,X_______,
  ___XX__X,X_______,
  ___XX__X,X_______,
  ___XX__X,X_______,
  ___XX__X,X_______,
  ___XX__X,X_______,
  ___XX___,XXXXXXX_,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontMicrosoftJhengHeiUI20_6001[ 40] = { /* code 6001 */
  ________,________,
  ________,________,
  ________,________,
  _______X,X_______,
  _______X,X_______,
  _XXXXXXX,XXXXXXX_,
  ______XX,XX______,
  ______X_,_X______,
  ____XXXX,_XX_____,
  ___XX__X,X_XX____,
  _XX_____,X___XX__,
  ___X_X_X,X____XX_,
  __XX_X__,XX__X___,
  __X__X__,_X__XX__,
  _XX__X__,___X_XX_,
  _X___XXX,XXXX__X_,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontMicrosoftJhengHeiUI20_6301[ 40] = { /* code 6301 */
  ________,________,
  ________,________,
  ___XX___,__X_____,
  ___XX___,__X_____,
  ___XX_XX,XXXXXXX_,
  _XXXXX__,__X_____,
  ___XX___,__X_____,
  ___XX__X,XXXXXX__,
  ___XXX__,________,
  ___XX___,____X___,
  __XXX_XX,XXXXXXX_,
  _X_XX__X,____X___,
  ___XX__X,X___X___,
  ___XX___,X___X___,
  ___XX___,XX__X___,
  ___XX___,____X___,
  __XX____,__XXX___,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontMicrosoftJhengHeiUI20_6570[ 40] = { /* code 6570 */
  ________,________,
  ________,________,
  ________,________,
  __X_XX_X,__XX____,
  __XXXXXX,__X_____,
  _XXXXXXX,X_XXXXX_,
  ____XXX_,_XX__X__,
  __X_XX_X,_X___X__,
  __XXXX_X,_X__XX__,
  _X__XX__,XX__XX__,
  ____X_XX,__X_X___,
  _XXXXXXX,X_X_X___,
  __XX__X_,__XXX___,
  __XX_XX_,__XX____,
  ____XXX_,__X_X___,
  ___XX_XX,XX__XX__,
  _XX_____,X_____X_,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontMicrosoftJhengHeiUI20_679C[ 40] = { /* code 679C */
  ________,________,
  ________,________,
  ________,________,
  __XXXXXX,XXXXXX__,
  __XX___X,X___XX__,
  __XXXXXX,XXXXXX__,
  __XX___X,X___XX__,
  __XX___X,X___XX__,
  __XXXXXX,XXXXXX__,
  _______X,X_______,
  _______X,X_______,
  _XXXXXXX,XXXXXXX_,
  ______XX,XX______,
  _____XXX,X_X_____,
  ____X__X,X__X____,
  __XX___X,X___XX__,
  _XX____X,X____XX_,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontMicrosoftJhengHeiUI20_68C0[ 40] = { /* code 68C0 */
  ________,________,
  ________,________,
  ________,________,
  ___X____,__X_____,
  ___X____,_XXX____,
  ___X____,XX_X____,
  _XXXXX__,X___X___,
  ___XX_XX,_____X__,
  __XXXXX_,XXXXX_X_,
  __XX_XXX,_XX__X__,
  _X_X___X,_XX__X__,
  _X_X___X,__X_XX__,
  ___X___X,__X_XX__,
  ___X___X,X_X_X___,
  ___X____,X__XX___,
  ___X__XX,XXXXXXX_,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontMicrosoftJhengHeiUI20_6B63[ 40] = { /* code 6B63 */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  _XXXXXXX,XXXXXXX_,
  ________,X_______,
  ________,X_______,
  ___X____,X_______,
  ___X____,X_______,
  ___X____,X_______,
  ___X____,XXXXXX__,
  ___X____,X_______,
  ___X____,X_______,
  ___X____,X_______,
  ___X____,X_______,
  ___X____,X_______,
  _XXXXXXX,XXXXXXX_,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontMicrosoftJhengHeiUI20_6D4B[ 40] = { /* code 6D4B */
  ________,________,
  ________,________,
  ________,________,
  __X__XXX,XX___XX_,
  __XX_X__,_X_X_XX_,
  ___X_X__,_X_X_XX_,
  _____X_X,_X_X_XX_,
  _XX__X_X,_X_X_XX_,
  __XX_X_X,_X_X_XX_,
  ___X_X_X,_X_X_XX_,
  _____X_X,_X_X_XX_,
  ___X_X_X,_X_X_XX_,
  __XX_X_X,_X_X_XX_,
  __X___XX,___X_XX_,
  __X___X_,X__X_XX_,
  _XX__X__,XX___XX_,
  _X_XX___,_X_XXX__,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontMicrosoftJhengHeiUI20_72B6[ 40] = { /* code 72B6 */
  ________,________,
  ________,________,
  ________,________,
  ____XX__,__X_____,
  ____XX__,__X_X___,
  _XX_XX__,__X_XX__,
  __X_XX__,__X__X__,
  __XXXXXX,XXXXXXX_,
  ____XX__,__X_____,
  ____XX__,_XXX____,
  ___XXX__,_X_X____,
  ___XXX__,_X_X____,
  __X_XX__,XX_XX___,
  _X__XX__,X___X___,
  ____XX_X,X___XX__,
  ____XXXX,_____X__,
  ____XXX_,______X_,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontMicrosoftJhengHeiUI20_7535[ 40] = { /* code 7535 */
  ________,________,
  ________,________,
  ________,________,
  _______X,X_______,
  _______X,X_______,
  __XXXXXX,XXXXXX__,
  __X____X,X____X__,
  __X____X,X____X__,
  __XXXXXX,XXXXXX__,
  __X____X,X____X__,
  __X____X,X____X__,
  __XXXXXX,XXXXXX__,
  _______X,X_______,
  _______X,X_____X_,
  _______X,X_____X_,
  _______X,XXXXXXX_,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontMicrosoftJhengHeiUI20_7C7B[ 40] = { /* code 7C7B */
  ________,________,
  ________,________,
  ________,________,
  ____X__X,X___X___,
  ____XX_X,X__XX___,
  _____X_X,X__X____,
  _XXXXXXX,XXXXXXX_,
  ____XX_X,X_______,
  ___XX__X,X_XXX___,
  _XX____X,X____XX_,
  ________,________,
  _______X,X_______,
  _XXXXXXX,XXXXXXX_,
  _______X,_X______,
  ______XX,X_XX____,
  ____XX__,____XX__,
  _XXX____,______X_,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontMicrosoftJhengHeiUI20_7E41[ 40] = { /* code 7E41 */
  ________,________,
  ________,________,
  ___XX___,__XX____,
  _XXXXXXX,X_XXXXX_,
  __XXXX_X,_X___X__,
  _XXXXXXX,XX__XX__,
  __XXXX_X,__X_X___,
  __X_XX_X,__XXX___,
  __XXXXXX,__XXX___,
  _____XXX,_XX__XX_,
  _______X,X_XX____,
  ___XXXXX,XXX_____,
  ______XX,X__XX___,
  ____XXX_,____XX__,
  __XXXXXX,XXXX_X__,
  ____XX_X,X_XXX___,
  _XXX__XX,X____XX_,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontMicrosoftJhengHeiUI20_7EBF[ 40] = { /* code 7EBF */
  ________,________,
  ________,________,
  ________,________,
  ____X___,_X_XX___,
  ___XX___,_X__XX__,
  ___X_X__,_X_XXX__,
  __X__XXX,XXX_____,
  _XXXXX__,_XX_____,
  _XXXX___,_XXXXXX_,
  ___X__XX,XXX_____,
  __X_XX__,_XX__X__,
  __XXX___,__X_XX__,
  _XX_____,__XXX___,
  _____XX_,_XXX__X_,
  ___XXX__,XX_XXXX_,
  _XX___XX,____XX__,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontMicrosoftJhengHeiUI20_7EC8[ 40] = { /* code 7EC8 */
  ________,________,
  ________,________,
  ________,________,
  ____X___,_XX_____,
  ___XX___,XXXXXX__,
  ___X_X__,X___XX__,
  __XX_XXX,XX__X___,
  _XX_XX_X,_XXX____,
  _XXXX___,_XXX____,
  ___XX___,XX_XX___,
  __XX__XX,_____XX_,
  __X_XX__,_X______,
  _XXX____,__XX____,
  ________,____X___,
  _____X__,XX______,
  ___XX_XX,__XX____,
  _XX_____,____X___,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontMicrosoftJhengHeiUI20_7ED3[ 40] = { /* code 7ED3 */
  ________,________,
  ________,________,
  ________,________,
  ____X___,__X_____,
  ___XX___,__X_____,
  ___X__XX,XXXXXXX_,
  __XX_X__,__X_____,
  __XXXX__,__X_____,
  _XXXXX_X,XXXXXXX_,
  ___XX___,________,
  ___X____,________,
  __X__X_X,XXXXXX__,
  _XXXXXXX,X____X__,
  _XX____X,X____X__,
  _____XXX,X____X__,
  ___XXX_X,XXXXXX__,
  _XX____X,X____X__,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontMicrosoftJhengHeiUI20_7EEA[ 40] = { /* code 7EEA */
  ________,________,
  ________,________,
  ____X___,_XX_____,
  ___XX___,_XX__XX_,
  ___X___X,XXXX_X__,
  __XX_X__,_XX_XX__,
  __X__X__,_XXXX___,
  _XXXXXXX,XXXXXXX_,
  _XX_X___,_XX_____,
  ___X____,XX______,
  ___X___X,XXXXXX__,
  __X_XXX_,X____X__,
  _XXXX___,X____X__,
  _XX_____,XXXXXX__,
  _____X__,X____X__,
  ___XX___,X____X__,
  _XX_____,XXXXXX__,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontMicrosoftJhengHeiUI20_7F06[ 40] = { /* code 7F06 */
  ________,________,
  ________,________,
  ________,________,
  ___XX___,_X_XX___,
  ___X__XX,_X_XXXX_,
  __XX_XXX,_XXXX___,
  __X_XXXX,_XX__X__,
  _XXXX_XX,_X___X__,
  _XXXX__X,XXXXXX__,
  ___X___X,_____X__,
  __XX___X,__X__X__,
  _XX_XX_X,__X__X__,
  _XXX___X,_XX__X__,
  _____X_X,_XXX_X__,
  __XXX___,XXXX__X_,
  _XX___XX,__XXXXX_,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontMicrosoftJhengHeiUI20_7F6E[ 40] = { /* code 7F6E */
  ________,________,
  ________,________,
  ________,________,
  __XXXXXX,XXXXXX__,
  __X___X_,_XX__X__,
  __XXXXXX,XXXXXX__,
  _______X,X_______,
  _XXXXXXX,XXXXXXX_,
  _______X,________,
  ___XXXXX,XXXXX___,
  ___X____,____X___,
  ___XXXXX,XXXXX___,
  ___X____,____X___,
  ___XXXXX,XXXXX___,
  ___X____,____X___,
  ___X____,____X___,
  _XXXXXXX,XXXXXXX_,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontMicrosoftJhengHeiUI20_88C5[ 40] = { /* code 88C5 */
  ________,________,
  ________,________,
  ________,________,
  __X_XX__,__X_____,
  __X_XXXX,XXXXXXX_,
  ___XXX__,__X_____,
  ___XXX__,__X_____,
  __XXXX_X,XXXXXX__,
  _X_____X,________,
  _______X,X_______,
  _XXXXXXX,XXXXXXX_,
  _____XX_,XX__X___,
  ____XX__,_X_XX___,
  __XXXX__,__XX____,
  _XX_XX__,X__X____,
  ____XXXX,____XX__,
  ____XX__,_____XX_,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontMicrosoftJhengHeiUI20_8BBE[ 40] = { /* code 8BBE */
  ________,________,
  ________,________,
  __X_____,________,
  __XX___X,XXXXX___,
  ___XX__X,___XX___,
  ___XX__X,___XX___,
  ______XX,___XX___,
  _XXX_XX_,____XXX_,
  ___X____,________,
  ___X____,________,
  ___X__XX,XXXXXX__,
  ___X___X,____X___,
  ___X___X,X__XX___,
  ___X_X__,XXXX____,
  ___XX___,_XX_____,
  ___X___X,X__XXX__,
  _____XX_,_____XX_,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontMicrosoftJhengHeiUI20_8D1F[ 40] = { /* code 8D1F */
  ________,________,
  ________,________,
  ________,________,
  _____XX_,________,
  _____XXX,XXXX____,
  ___XX___,__XX____,
  __XX____,_XX_____,
  _XXXXXXX,XXXXX___,
  ___X____,____X___,
  ___X___X,X___X___,
  ___X___X,X___X___,
  ___X___X,X___X___,
  ___X___X,X___X___,
  ___X___X,____X___,
  ______XX,_XX_____,
  ____XXX_,__XXX___,
  _XXX____,_____XX_,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontMicrosoftJhengHeiUI20_8DEF[ 40] = { /* code 8DEF */
  ________,________,
  ________,________,
  ________,________,
  __XXXX__,_XX_____,
  __X__X__,XXXXXX__,
  __X__X_X,XX__XX__,
  __X__X_X,_X_XX___,
  __XXXX__,_XXX____,
  ____X___,XXXXXX__,
  __X_X__X,X____XX_,
  __X_XXX_,________,
  __X_X___,XXXXXX__,
  __X_X___,X____X__,
  __X_X___,X____X__,
  __X_XXX_,X____X__,
  __XXXX__,XXXXXX__,
  _XX_____,X____X__,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontMicrosoftJhengHeiUI20_8F74[ 40] = { /* code 8F74 */
  ________,________,
  ________,________,
  ___X____,__XX____,
  ___X____,__XX____,
  _XXXXXX_,__XX____,
  __X____X,XXXXXXX_,
  __X_X__X,X_XX_XX_,
  __X_X__X,X_XX_XX_,
  _XX_X__X,X_XX_XX_,
  _XXXXXXX,X_XX_XX_,
  ____X__X,XXXXXXX_,
  ____X__X,X_XX_XX_,
  ____XXXX,X_XX_XX_,
  _XXXX__X,X_XX_XX_,
  ____X__X,X_XX_XX_,
  ____X__X,XXXXXXX_,
  ____X__X,X____XX_,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontMicrosoftJhengHeiUI20_8F7D[ 40] = { /* code 8F7D */
  ________,________,
  ________,________,
  ________,________,
  _____X__,__X_____,
  __XXXXXX,X_X__X__,
  _____X__,__X__X__,
  _XXXXXXX,XXXXXXX_,
  ____X___,__XX____,
  ____X___,__XX____,
  _XXXXXXX,X_XX_X__,
  __XX_XX_,__XX_X__,
  __XXXXXX,X__XXX__,
  _____XX_,___XX___,
  _____XXX,X__X__X_,
  _XXXXXX_,__XXX_X_,
  _____XX_,_XX_XXX_,
  _____XX_,XX__XX__,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontMicrosoftJhengHeiUI20_957F[ 40] = { /* code 957F */
  ________,________,
  ________,________,
  ________,________,
  ____X___,____XX__,
  ____X___,___XX___,
  ____X___,_XX_____,
  ____X__X,XX______,
  ____XXX_,________,
  ____X___,________,
  _XXXXXXX,XXXXXXX_,
  ____X__X,X_______,
  ____X___,X_______,
  ____X___,_X______,
  ____X___,_XX_____,
  ____X__X,X_XX____,
  ____XXXX,____XX__,
  ____XX__,_____XX_,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontMicrosoftJhengHeiUI20_963B[ 40] = { /* code 963B */
  ________,________,
  ________,________,
  ________,________,
  _XXXXX_X,XXXXXX__,
  _XX_XX_X,____XX__,
  _XX_XX_X,____XX__,
  _XX_X__X,____XX__,
  _XXXX__X,XXXXXX__,
  _XX_X__X,____XX__,
  _XX_XX_X,____XX__,
  _XX__X_X,____XX__,
  _XX__X_X,XXXXXX__,
  _XX__X_X,____XX__,
  _XXXX__X,____XX__,
  _XX____X,____XX__,
  _XX____X,____XX__,
  _XX___XX,XXXXXXX_,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE GUI_CHARINFO GUI_FontMicrosoftJhengHeiUI20_CharInfo[62] = {
   {   6,   6,  1, acGUI_FontMicrosoftJhengHeiUI20_0028 } /* code 0028 */
  ,{   6,   6,  1, acGUI_FontMicrosoftJhengHeiUI20_0029 } /* code 0029 */
  ,{   4,   4,  1, acGUI_FontMicrosoftJhengHeiUI20_002E } /* code 002E */
  ,{   7,   7,  1, acGUI_FontMicrosoftJhengHeiUI20_002F } /* code 002F */
  ,{  10,  10,  2, acGUI_FontMicrosoftJhengHeiUI20_0030 } /* code 0030 */
  ,{  10,  10,  2, acGUI_FontMicrosoftJhengHeiUI20_0031 } /* code 0031 */
  ,{  10,  10,  2, acGUI_FontMicrosoftJhengHeiUI20_0032 } /* code 0032 */
  ,{  10,  10,  2, acGUI_FontMicrosoftJhengHeiUI20_0033 } /* code 0033 */
  ,{  10,  10,  2, acGUI_FontMicrosoftJhengHeiUI20_0034 } /* code 0034 */
  ,{  10,  10,  2, acGUI_FontMicrosoftJhengHeiUI20_0035 } /* code 0035 */
  ,{  10,  10,  2, acGUI_FontMicrosoftJhengHeiUI20_0036 } /* code 0036 */
  ,{  10,  10,  2, acGUI_FontMicrosoftJhengHeiUI20_0037 } /* code 0037 */
  ,{  10,  10,  2, acGUI_FontMicrosoftJhengHeiUI20_0038 } /* code 0038 */
  ,{  10,  10,  2, acGUI_FontMicrosoftJhengHeiUI20_0039 } /* code 0039 */
  ,{   4,   4,  1, acGUI_FontMicrosoftJhengHeiUI20_003A } /* code 003A */
  ,{   9,   9,  2, acGUI_FontMicrosoftJhengHeiUI20_0046 } /* code 0046 */
  ,{  10,  10,  2, acGUI_FontMicrosoftJhengHeiUI20_004B } /* code 004B */
  ,{   8,   8,  1, acGUI_FontMicrosoftJhengHeiUI20_0063 } /* code 0063 */
  ,{  15,  15,  2, acGUI_FontMicrosoftJhengHeiUI20_006D } /* code 006D */
  ,{  10,  10,  2, acGUI_FontMicrosoftJhengHeiUI20_006E } /* code 006E */
  ,{  10,  10,  2, acGUI_FontMicrosoftJhengHeiUI20_0070 } /* code 0070 */
  ,{  13,  13,  2, acGUI_FontMicrosoftJhengHeiUI20_03A9 } /* code 03A9 */
  ,{  16,  16,  2, acGUI_FontMicrosoftJhengHeiUI20_3001 } /* code 3001 */
  ,{  16,  16,  2, acGUI_FontMicrosoftJhengHeiUI20_4E0E } /* code 4E0E */
  ,{  16,  16,  2, acGUI_FontMicrosoftJhengHeiUI20_4F5C } /* code 4F5C */
  ,{  16,  16,  2, acGUI_FontMicrosoftJhengHeiUI20_4FDD } /* code 4FDD */
  ,{  16,  16,  2, acGUI_FontMicrosoftJhengHeiUI20_53C2 } /* code 53C2 */
  ,{  16,  16,  2, acGUI_FontMicrosoftJhengHeiUI20_540C } /* code 540C */
  ,{  16,  16,  2, acGUI_FontMicrosoftJhengHeiUI20_5728 } /* code 5728 */
  ,{  16,  16,  2, acGUI_FontMicrosoftJhengHeiUI20_578B } /* code 578B */
  ,{  16,  16,  2, acGUI_FontMicrosoftJhengHeiUI20_5907 } /* code 5907 */
  ,{  16,  16,  2, acGUI_FontMicrosoftJhengHeiUI20_5BB9 } /* code 5BB9 */
  ,{  16,  16,  2, acGUI_FontMicrosoftJhengHeiUI20_5C31 } /* code 5C31 */
  ,{  16,  16,  2, acGUI_FontMicrosoftJhengHeiUI20_5DE5 } /* code 5DE5 */
  ,{  16,  16,  2, acGUI_FontMicrosoftJhengHeiUI20_5EA6 } /* code 5EA6 */
  ,{  16,  16,  2, acGUI_FontMicrosoftJhengHeiUI20_5F00 } /* code 5F00 */
  ,{  16,  16,  2, acGUI_FontMicrosoftJhengHeiUI20_5FD9 } /* code 5FD9 */
  ,{  16,  16,  2, acGUI_FontMicrosoftJhengHeiUI20_6001 } /* code 6001 */
  ,{  16,  16,  2, acGUI_FontMicrosoftJhengHeiUI20_6301 } /* code 6301 */
  ,{  16,  16,  2, acGUI_FontMicrosoftJhengHeiUI20_6570 } /* code 6570 */
  ,{  16,  16,  2, acGUI_FontMicrosoftJhengHeiUI20_679C } /* code 679C */
  ,{  16,  16,  2, acGUI_FontMicrosoftJhengHeiUI20_68C0 } /* code 68C0 */
  ,{  16,  16,  2, acGUI_FontMicrosoftJhengHeiUI20_6B63 } /* code 6B63 */
  ,{  16,  16,  2, acGUI_FontMicrosoftJhengHeiUI20_6D4B } /* code 6D4B */
  ,{  16,  16,  2, acGUI_FontMicrosoftJhengHeiUI20_72B6 } /* code 72B6 */
  ,{  16,  16,  2, acGUI_FontMicrosoftJhengHeiUI20_7535 } /* code 7535 */
  ,{  16,  16,  2, acGUI_FontMicrosoftJhengHeiUI20_7C7B } /* code 7C7B */
  ,{  16,  16,  2, acGUI_FontMicrosoftJhengHeiUI20_7E41 } /* code 7E41 */
  ,{  16,  16,  2, acGUI_FontMicrosoftJhengHeiUI20_7EBF } /* code 7EBF */
  ,{  16,  16,  2, acGUI_FontMicrosoftJhengHeiUI20_7EC8 } /* code 7EC8 */
  ,{  16,  16,  2, acGUI_FontMicrosoftJhengHeiUI20_7ED3 } /* code 7ED3 */
  ,{  16,  16,  2, acGUI_FontMicrosoftJhengHeiUI20_7EEA } /* code 7EEA */
  ,{  16,  16,  2, acGUI_FontMicrosoftJhengHeiUI20_7F06 } /* code 7F06 */
  ,{  16,  16,  2, acGUI_FontMicrosoftJhengHeiUI20_7F6E } /* code 7F6E */
  ,{  16,  16,  2, acGUI_FontMicrosoftJhengHeiUI20_88C5 } /* code 88C5 */
  ,{  16,  16,  2, acGUI_FontMicrosoftJhengHeiUI20_8BBE } /* code 8BBE */
  ,{  16,  16,  2, acGUI_FontMicrosoftJhengHeiUI20_8D1F } /* code 8D1F */
  ,{  16,  16,  2, acGUI_FontMicrosoftJhengHeiUI20_8DEF } /* code 8DEF */
  ,{  16,  16,  2, acGUI_FontMicrosoftJhengHeiUI20_8F74 } /* code 8F74 */
  ,{  16,  16,  2, acGUI_FontMicrosoftJhengHeiUI20_8F7D } /* code 8F7D */
  ,{  16,  16,  2, acGUI_FontMicrosoftJhengHeiUI20_957F } /* code 957F */
  ,{  16,  16,  2, acGUI_FontMicrosoftJhengHeiUI20_963B } /* code 963B */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontMicrosoftJhengHeiUI20_Prop48 = {
   0x963B /* first character */
  ,0x963B /* last character  */
  ,&GUI_FontMicrosoftJhengHeiUI20_CharInfo[ 61] /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP *)0 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontMicrosoftJhengHeiUI20_Prop47 = {
   0x957F /* first character */
  ,0x957F /* last character  */
  ,&GUI_FontMicrosoftJhengHeiUI20_CharInfo[ 60] /* address of first character */
  ,&GUI_FontMicrosoftJhengHeiUI20_Prop48 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontMicrosoftJhengHeiUI20_Prop46 = {
   0x8F7D /* first character */
  ,0x8F7D /* last character  */
  ,&GUI_FontMicrosoftJhengHeiUI20_CharInfo[ 59] /* address of first character */
  ,&GUI_FontMicrosoftJhengHeiUI20_Prop47 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontMicrosoftJhengHeiUI20_Prop45 = {
   0x8F74 /* first character */
  ,0x8F74 /* last character  */
  ,&GUI_FontMicrosoftJhengHeiUI20_CharInfo[ 58] /* address of first character */
  ,&GUI_FontMicrosoftJhengHeiUI20_Prop46 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontMicrosoftJhengHeiUI20_Prop44 = {
   0x8DEF /* first character */
  ,0x8DEF /* last character  */
  ,&GUI_FontMicrosoftJhengHeiUI20_CharInfo[ 57] /* address of first character */
  ,&GUI_FontMicrosoftJhengHeiUI20_Prop45 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontMicrosoftJhengHeiUI20_Prop43 = {
   0x8D1F /* first character */
  ,0x8D1F /* last character  */
  ,&GUI_FontMicrosoftJhengHeiUI20_CharInfo[ 56] /* address of first character */
  ,&GUI_FontMicrosoftJhengHeiUI20_Prop44 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontMicrosoftJhengHeiUI20_Prop42 = {
   0x8BBE /* first character */
  ,0x8BBE /* last character  */
  ,&GUI_FontMicrosoftJhengHeiUI20_CharInfo[ 55] /* address of first character */
  ,&GUI_FontMicrosoftJhengHeiUI20_Prop43 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontMicrosoftJhengHeiUI20_Prop41 = {
   0x88C5 /* first character */
  ,0x88C5 /* last character  */
  ,&GUI_FontMicrosoftJhengHeiUI20_CharInfo[ 54] /* address of first character */
  ,&GUI_FontMicrosoftJhengHeiUI20_Prop42 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontMicrosoftJhengHeiUI20_Prop40 = {
   0x7F6E /* first character */
  ,0x7F6E /* last character  */
  ,&GUI_FontMicrosoftJhengHeiUI20_CharInfo[ 53] /* address of first character */
  ,&GUI_FontMicrosoftJhengHeiUI20_Prop41 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontMicrosoftJhengHeiUI20_Prop39 = {
   0x7F06 /* first character */
  ,0x7F06 /* last character  */
  ,&GUI_FontMicrosoftJhengHeiUI20_CharInfo[ 52] /* address of first character */
  ,&GUI_FontMicrosoftJhengHeiUI20_Prop40 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontMicrosoftJhengHeiUI20_Prop38 = {
   0x7EEA /* first character */
  ,0x7EEA /* last character  */
  ,&GUI_FontMicrosoftJhengHeiUI20_CharInfo[ 51] /* address of first character */
  ,&GUI_FontMicrosoftJhengHeiUI20_Prop39 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontMicrosoftJhengHeiUI20_Prop37 = {
   0x7ED3 /* first character */
  ,0x7ED3 /* last character  */
  ,&GUI_FontMicrosoftJhengHeiUI20_CharInfo[ 50] /* address of first character */
  ,&GUI_FontMicrosoftJhengHeiUI20_Prop38 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontMicrosoftJhengHeiUI20_Prop36 = {
   0x7EC8 /* first character */
  ,0x7EC8 /* last character  */
  ,&GUI_FontMicrosoftJhengHeiUI20_CharInfo[ 49] /* address of first character */
  ,&GUI_FontMicrosoftJhengHeiUI20_Prop37 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontMicrosoftJhengHeiUI20_Prop35 = {
   0x7EBF /* first character */
  ,0x7EBF /* last character  */
  ,&GUI_FontMicrosoftJhengHeiUI20_CharInfo[ 48] /* address of first character */
  ,&GUI_FontMicrosoftJhengHeiUI20_Prop36 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontMicrosoftJhengHeiUI20_Prop34 = {
   0x7E41 /* first character */
  ,0x7E41 /* last character  */
  ,&GUI_FontMicrosoftJhengHeiUI20_CharInfo[ 47] /* address of first character */
  ,&GUI_FontMicrosoftJhengHeiUI20_Prop35 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontMicrosoftJhengHeiUI20_Prop33 = {
   0x7C7B /* first character */
  ,0x7C7B /* last character  */
  ,&GUI_FontMicrosoftJhengHeiUI20_CharInfo[ 46] /* address of first character */
  ,&GUI_FontMicrosoftJhengHeiUI20_Prop34 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontMicrosoftJhengHeiUI20_Prop32 = {
   0x7535 /* first character */
  ,0x7535 /* last character  */
  ,&GUI_FontMicrosoftJhengHeiUI20_CharInfo[ 45] /* address of first character */
  ,&GUI_FontMicrosoftJhengHeiUI20_Prop33 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontMicrosoftJhengHeiUI20_Prop31 = {
   0x72B6 /* first character */
  ,0x72B6 /* last character  */
  ,&GUI_FontMicrosoftJhengHeiUI20_CharInfo[ 44] /* address of first character */
  ,&GUI_FontMicrosoftJhengHeiUI20_Prop32 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontMicrosoftJhengHeiUI20_Prop30 = {
   0x6D4B /* first character */
  ,0x6D4B /* last character  */
  ,&GUI_FontMicrosoftJhengHeiUI20_CharInfo[ 43] /* address of first character */
  ,&GUI_FontMicrosoftJhengHeiUI20_Prop31 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontMicrosoftJhengHeiUI20_Prop29 = {
   0x6B63 /* first character */
  ,0x6B63 /* last character  */
  ,&GUI_FontMicrosoftJhengHeiUI20_CharInfo[ 42] /* address of first character */
  ,&GUI_FontMicrosoftJhengHeiUI20_Prop30 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontMicrosoftJhengHeiUI20_Prop28 = {
   0x68C0 /* first character */
  ,0x68C0 /* last character  */
  ,&GUI_FontMicrosoftJhengHeiUI20_CharInfo[ 41] /* address of first character */
  ,&GUI_FontMicrosoftJhengHeiUI20_Prop29 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontMicrosoftJhengHeiUI20_Prop27 = {
   0x679C /* first character */
  ,0x679C /* last character  */
  ,&GUI_FontMicrosoftJhengHeiUI20_CharInfo[ 40] /* address of first character */
  ,&GUI_FontMicrosoftJhengHeiUI20_Prop28 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontMicrosoftJhengHeiUI20_Prop26 = {
   0x6570 /* first character */
  ,0x6570 /* last character  */
  ,&GUI_FontMicrosoftJhengHeiUI20_CharInfo[ 39] /* address of first character */
  ,&GUI_FontMicrosoftJhengHeiUI20_Prop27 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontMicrosoftJhengHeiUI20_Prop25 = {
   0x6301 /* first character */
  ,0x6301 /* last character  */
  ,&GUI_FontMicrosoftJhengHeiUI20_CharInfo[ 38] /* address of first character */
  ,&GUI_FontMicrosoftJhengHeiUI20_Prop26 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontMicrosoftJhengHeiUI20_Prop24 = {
   0x6001 /* first character */
  ,0x6001 /* last character  */
  ,&GUI_FontMicrosoftJhengHeiUI20_CharInfo[ 37] /* address of first character */
  ,&GUI_FontMicrosoftJhengHeiUI20_Prop25 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontMicrosoftJhengHeiUI20_Prop23 = {
   0x5FD9 /* first character */
  ,0x5FD9 /* last character  */
  ,&GUI_FontMicrosoftJhengHeiUI20_CharInfo[ 36] /* address of first character */
  ,&GUI_FontMicrosoftJhengHeiUI20_Prop24 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontMicrosoftJhengHeiUI20_Prop22 = {
   0x5F00 /* first character */
  ,0x5F00 /* last character  */
  ,&GUI_FontMicrosoftJhengHeiUI20_CharInfo[ 35] /* address of first character */
  ,&GUI_FontMicrosoftJhengHeiUI20_Prop23 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontMicrosoftJhengHeiUI20_Prop21 = {
   0x5EA6 /* first character */
  ,0x5EA6 /* last character  */
  ,&GUI_FontMicrosoftJhengHeiUI20_CharInfo[ 34] /* address of first character */
  ,&GUI_FontMicrosoftJhengHeiUI20_Prop22 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontMicrosoftJhengHeiUI20_Prop20 = {
   0x5DE5 /* first character */
  ,0x5DE5 /* last character  */
  ,&GUI_FontMicrosoftJhengHeiUI20_CharInfo[ 33] /* address of first character */
  ,&GUI_FontMicrosoftJhengHeiUI20_Prop21 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontMicrosoftJhengHeiUI20_Prop19 = {
   0x5C31 /* first character */
  ,0x5C31 /* last character  */
  ,&GUI_FontMicrosoftJhengHeiUI20_CharInfo[ 32] /* address of first character */
  ,&GUI_FontMicrosoftJhengHeiUI20_Prop20 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontMicrosoftJhengHeiUI20_Prop18 = {
   0x5BB9 /* first character */
  ,0x5BB9 /* last character  */
  ,&GUI_FontMicrosoftJhengHeiUI20_CharInfo[ 31] /* address of first character */
  ,&GUI_FontMicrosoftJhengHeiUI20_Prop19 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontMicrosoftJhengHeiUI20_Prop17 = {
   0x5907 /* first character */
  ,0x5907 /* last character  */
  ,&GUI_FontMicrosoftJhengHeiUI20_CharInfo[ 30] /* address of first character */
  ,&GUI_FontMicrosoftJhengHeiUI20_Prop18 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontMicrosoftJhengHeiUI20_Prop16 = {
   0x578B /* first character */
  ,0x578B /* last character  */
  ,&GUI_FontMicrosoftJhengHeiUI20_CharInfo[ 29] /* address of first character */
  ,&GUI_FontMicrosoftJhengHeiUI20_Prop17 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontMicrosoftJhengHeiUI20_Prop15 = {
   0x5728 /* first character */
  ,0x5728 /* last character  */
  ,&GUI_FontMicrosoftJhengHeiUI20_CharInfo[ 28] /* address of first character */
  ,&GUI_FontMicrosoftJhengHeiUI20_Prop16 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontMicrosoftJhengHeiUI20_Prop14 = {
   0x540C /* first character */
  ,0x540C /* last character  */
  ,&GUI_FontMicrosoftJhengHeiUI20_CharInfo[ 27] /* address of first character */
  ,&GUI_FontMicrosoftJhengHeiUI20_Prop15 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontMicrosoftJhengHeiUI20_Prop13 = {
   0x53C2 /* first character */
  ,0x53C2 /* last character  */
  ,&GUI_FontMicrosoftJhengHeiUI20_CharInfo[ 26] /* address of first character */
  ,&GUI_FontMicrosoftJhengHeiUI20_Prop14 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontMicrosoftJhengHeiUI20_Prop12 = {
   0x4FDD /* first character */
  ,0x4FDD /* last character  */
  ,&GUI_FontMicrosoftJhengHeiUI20_CharInfo[ 25] /* address of first character */
  ,&GUI_FontMicrosoftJhengHeiUI20_Prop13 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontMicrosoftJhengHeiUI20_Prop11 = {
   0x4F5C /* first character */
  ,0x4F5C /* last character  */
  ,&GUI_FontMicrosoftJhengHeiUI20_CharInfo[ 24] /* address of first character */
  ,&GUI_FontMicrosoftJhengHeiUI20_Prop12 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontMicrosoftJhengHeiUI20_Prop10 = {
   0x4E0E /* first character */
  ,0x4E0E /* last character  */
  ,&GUI_FontMicrosoftJhengHeiUI20_CharInfo[ 23] /* address of first character */
  ,&GUI_FontMicrosoftJhengHeiUI20_Prop11 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontMicrosoftJhengHeiUI20_Prop9 = {
   0x3001 /* first character */
  ,0x3001 /* last character  */
  ,&GUI_FontMicrosoftJhengHeiUI20_CharInfo[ 22] /* address of first character */
  ,&GUI_FontMicrosoftJhengHeiUI20_Prop10 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontMicrosoftJhengHeiUI20_Prop8 = {
   0x03A9 /* first character */
  ,0x03A9 /* last character  */
  ,&GUI_FontMicrosoftJhengHeiUI20_CharInfo[ 21] /* address of first character */
  ,&GUI_FontMicrosoftJhengHeiUI20_Prop9 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontMicrosoftJhengHeiUI20_Prop7 = {
   0x0070 /* first character */
  ,0x0070 /* last character  */
  ,&GUI_FontMicrosoftJhengHeiUI20_CharInfo[ 20] /* address of first character */
  ,&GUI_FontMicrosoftJhengHeiUI20_Prop8 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontMicrosoftJhengHeiUI20_Prop6 = {
   0x006D /* first character */
  ,0x006E /* last character  */
  ,&GUI_FontMicrosoftJhengHeiUI20_CharInfo[ 18] /* address of first character */
  ,&GUI_FontMicrosoftJhengHeiUI20_Prop7 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontMicrosoftJhengHeiUI20_Prop5 = {
   0x0063 /* first character */
  ,0x0063 /* last character  */
  ,&GUI_FontMicrosoftJhengHeiUI20_CharInfo[ 17] /* address of first character */
  ,&GUI_FontMicrosoftJhengHeiUI20_Prop6 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontMicrosoftJhengHeiUI20_Prop4 = {
   0x004B /* first character */
  ,0x004B /* last character  */
  ,&GUI_FontMicrosoftJhengHeiUI20_CharInfo[ 16] /* address of first character */
  ,&GUI_FontMicrosoftJhengHeiUI20_Prop5 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontMicrosoftJhengHeiUI20_Prop3 = {
   0x0046 /* first character */
  ,0x0046 /* last character  */
  ,&GUI_FontMicrosoftJhengHeiUI20_CharInfo[ 15] /* address of first character */
  ,&GUI_FontMicrosoftJhengHeiUI20_Prop4 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontMicrosoftJhengHeiUI20_Prop2 = {
   0x002E /* first character */
  ,0x003A /* last character  */
  ,&GUI_FontMicrosoftJhengHeiUI20_CharInfo[  2] /* address of first character */
  ,&GUI_FontMicrosoftJhengHeiUI20_Prop3 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontMicrosoftJhengHeiUI20_Prop1 = {
   0x0028 /* first character */
  ,0x0029 /* last character  */
  ,&GUI_FontMicrosoftJhengHeiUI20_CharInfo[  0] /* address of first character */
  ,&GUI_FontMicrosoftJhengHeiUI20_Prop2 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT GUI_FontMicrosoftJhengHeiUI20 = {
   GUI_FONTTYPE_PROP /* type of font    */
  ,20 /* height of font  */
  ,20 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,{&GUI_FontMicrosoftJhengHeiUI20_Prop1}
  ,16 /* Baseline */
  ,9 /* Height of lowercase characters */
  ,12 /* Height of capital characters */
};

