/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        emWin Font Converter (ST) version 5.44                      *
*        Compiled Nov 10 2017, 08:53:23                              *
*                                                                    *
*        (c) 1998 - 2017 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: Microsoft JhengHei UI32.c                             *
* Font:        Microsoft JhengHei UI                                 *
* Height:      32                                                    *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height:  32                                           *
* Range disabled:       0000 - FFFF                                  *
* Read pattern file: C:\Users\a9286\Desktop\2.txt                    *
*                                                                    *
**********************************************************************
*/

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font.
*/
extern GUI_CONST_STORAGE GUI_FONT GUI_FontMicrosoftJhengHeiUI32;

/* Start of unicode area <Basic Latin> */
GUI_CONST_STORAGE unsigned char acGUI_FontMicrosoftJhengHeiUI32_0020[  1] = { /* code 0020, SPACE */
  ________};

/* Start of unicode area <CJK Unified Ideographs> */
GUI_CONST_STORAGE unsigned char acGUI_FontMicrosoftJhengHeiUI32_4E0E[ 63] = { /* code 4E0E */
  ___XX___,________,________,
  ___XX___,________,________,
  ___XX___,________,________,
  ___XXXXX,XXXXXXXX,XXX_____,
  ___XXXXX,XXXXXXXX,XXX_____,
  ___XX___,________,________,
  ___XX___,________,________,
  ___XX___,________,________,
  ___XX___,________,________,
  ___XXXXX,XXXXXXXX,XXXXX___,
  ___XXXXX,XXXXXXXX,XXXXX___,
  ________,________,___XX___,
  ________,________,___XX___,
  ________,________,__XXX___,
  XXXXXXXX,XXXXXXXX,X_XXX___,
  XXXXXXXX,XXXXXXXX,X_XXX___,
  ________,________,__XX____,
  ________,________,__XX____,
  ________,________,__XX____,
  ________,____XXXX,XXXX____,
  ________,____XXXX,XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontMicrosoftJhengHeiUI32_540C[ 63] = { /* code 540C */
  XXXXXXXX,XXXXXXXX,XXXX____,
  XXXXXXXX,XXXXXXXX,XXXX____,
  XX______,________,_XXX____,
  XX______,________,_XXX____,
  XX______,________,_XXX____,
  XX_XXXXX,XXXXXXXX,_XXX____,
  XX_XXXXX,XXXXXXXX,_XXX____,
  XX______,________,_XXX____,
  XX______,________,_XXX____,
  XX___XXX,XXXXXXX_,_XXX____,
  XX___XXX,XXXXXXX_,_XXX____,
  XX___XX_,_____XX_,_XXX____,
  XX___XX_,_____XX_,_XXX____,
  XX___XX_,_____XX_,_XXX____,
  XX___XX_,_____XX_,_XXX____,
  XX___XXX,XXXXXXX_,_XXX____,
  XX___XXX,XXXXXXX_,_XXX____,
  XX______,________,_XXX____,
  XX______,________,_XXX____,
  XX______,_____XXX,XXXX____,
  XX______,_____XXX,XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontMicrosoftJhengHeiUI32_5EA6[ 69] = { /* code 5EA6 */
  ________,_XXX____,________,
  ________,_XXX____,________,
  ________,__XX____,________,
  __XXXXXX,XXXXXXXX,XXXXX___,
  __XXXXXX,XXXXXXXX,XXXXX___,
  __XX____,________,________,
  __XX____,XX_____X,XX______,
  __XX____,XX_____X,XX______,
  __XX_XXX,XXXXXXXX,XXXXX___,
  __XX_XXX,XXXXXXXX,XXXXX___,
  __XX____,XX_____X,XX______,
  __XX____,XX_____X,XX______,
  __XX____,XXXXXXXX,XX______,
  __XX____,XXXXXXXX,XX______,
  __XX____,________,________,
  __XX__XX,XXXXXXXX,XXX_____,
  __XX__XX,XXXXXXXX,XXX_____,
  _XXX___X,XX_____X,XX______,
  _XX_____,XXX___XX,X_______,
  _XX_____,_XXXXXXX,________,
  XXX_____,_XXXXXXX,X_______,
  XX__XXXX,XXXX_XXX,XXXXX___,
  _X___XXX,________,_XXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontMicrosoftJhengHeiUI32_68C0[ 69] = { /* code 68C0 */
  ____XX__,_______X,X_______,
  ____XX__,______XX,X_______,
  ____XX__,______XX,X_______,
  ____XX__,_____XX_,XX______,
  ____XX__,____XX__,XX______,
  _XXXXXXX,___XXX__,_XX_____,
  _XXXXXXX,__XXX___,__XX____,
  ____XX__,_XXX____,___XX___,
  ___XXXX_,XXXXXXXX,XXX_XX__,
  ___XXXXX,XX_XXXXX,XXX__X__,
  __XXXXXX,_XX_____,________,
  __X_XX_X,XXX___X_,___XX___,
  _XX_XX__,_XX__XXX,___XX___,
  _XX_XX__,__XX__XX,___XX___,
  _X__XX__,__XX__XX,__XXX___,
  _X__XX__,__XX__XX,__XX____,
  ____XX__,__XXX_XX,__XX____,
  ____XX__,___XX_XX,__XX____,
  ____XX__,___X__XX,_XX_____,
  ____XX__,________,_XX_____,
  ____XX__,XXXXXXXX,XXXXXX__,
  ____XX__,XXXXXXXX,XXXXXX__,
  ____XX__,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontMicrosoftJhengHeiUI32_6D4B[ 69] = { /* code 6D4B */
  __X_____,________,________,
  _XXX__XX,XXXXXXX_,____XX__,
  __XXX_XX,XXXXXXX_,XX__XX__,
  ___XXXXX,_____XX_,XX__XX__,
  ____X_XX,_____XX_,XX__XX__,
  ______XX,_XX__XX_,XX__XX__,
  ______XX,_XX__XX_,XX__XX__,
  _XX___XX,_XX__XX_,XX__XX__,
  __XX__XX,_XX__XX_,XX__XX__,
  ___XXXXX,_XX__XX_,XX__XX__,
  ______XX,_XX__XX_,XX__XX__,
  ______XX,_XX__XX_,XX__XX__,
  ______XX,_XX__XX_,XX__XX__,
  ___X__XX,_XX__XX_,XX__XX__,
  ___XX_XX,_XX__XX_,XX__XX__,
  ___XX_XX,_XX__XX_,XX__XX__,
  __XX__XX,_XX__XX_,XX__XX__,
  __XX____,_XX_____,XX__XX__,
  __XX____,XX__X___,XX__XX__,
  _XX____X,X___XX__,____XX__,
  _XX___XX,____XXX_,____XX__,
  _X___XX_,_____XX_,_XXXXX__,
  ________,_____X__,_XXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontMicrosoftJhengHeiUI32_7535[ 66] = { /* code 7535 */
  ________,XX______,________,
  ________,XX______,________,
  ________,XX______,________,
  ________,XX______,________,
  XXXXXXXX,XXXXXXXX,XXX_____,
  XXXXXXXX,XXXXXXXX,XXX_____,
  XX______,XX______,_XX_____,
  XX______,XX______,_XX_____,
  XX______,XX______,_XX_____,
  XXXXXXXX,XXXXXXXX,XXX_____,
  XXXXXXXX,XXXXXXXX,XXX_____,
  XX______,XX______,_XX_____,
  XX______,XX______,_XX_____,
  XX______,XX______,_XX_____,
  XXXXXXXX,XXXXXXXX,XXX_____,
  XXXXXXXX,XXXXXXXX,XXX_____,
  ________,XX______,________,
  ________,XX______,__XX____,
  ________,XX______,__XXX___,
  ________,XX______,__XX____,
  ________,XXXXXXXX,XXXX____,
  ________,_XXXXXXX,XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontMicrosoftJhengHeiUI32_7F06[ 66] = { /* code 7F06 */
  ____XX__,____XX__,_XX_____,
  ____XX__,_XX_XX__,_XX_____,
  ____XX__,_XX_XX__,XXXXXX__,
  ___XXX__,_XX_XX__,XXXXXX__,
  ___XX_XX,_XX_XX_X,XX_X____,
  __XXX_XX,XXX_XX_X,X_XXX___,
  __XX__XX,_XX_XX__,___XX___,
  __XX_XX_,_XX_XX__,____X___,
  _XXXXXX_,_XX_____,________,
  _XXXXXX_,_XXXXXXX,XXXXX___,
  ____XX__,_XXXXXXX,XXXXX___,
  ___XX___,_XXX____,___XX___,
  ___XX___,_XXX__XX,___XX___,
  __XX___X,_XXX__XX,___XX___,
  __XXXXXX,_XXX__XX,___XX___,
  _XXXXXX_,_XXX__XX,___XX___,
  _XX_____,_XXX__XX,X__XX___,
  _______X,_____XXX,X_______,
  _____XXX,X____XXX,X____X__,
  __XXXXXX,___XXX_X,X___XX__,
  _XXXX___,__XX___X,XXXXXX__,
  _XX_____,XX______,XXXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontMicrosoftJhengHeiUI32_7F6E[ 63] = { /* code 7F6E */
  _XXXXXXX,XXXXXXXX,XXXX____,
  _XX____X,X___XXX_,__XX____,
  _XX____X,X___XXX_,__XX____,
  _XXXXXXX,XXXXXXXX,XXXX____,
  ________,_XXX____,________,
  ________,_XXX____,________,
  XXXXXXXX,XXXXXXXX,XXXXX___,
  ________,_XX_____,________,
  ________,_XX_____,________,
  __XXXXXX,XXXXXXXX,XXX_____,
  __XXX___,________,XXX_____,
  __XXXXXX,XXXXXXXX,XXX_____,
  __XXX___,________,XXX_____,
  __XXX___,________,XXX_____,
  __XXXXXX,XXXXXXXX,XXX_____,
  __XXX___,________,XXX_____,
  __XXX___,________,XXX_____,
  __XXXXXX,XXXXXXXX,XXX_____,
  __XXX___,________,XXX_____,
  __XXX___,________,XXX_____,
  XXXXXXXX,XXXXXXXX,XXXXXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontMicrosoftJhengHeiUI32_88C5[ 63] = { /* code 88C5 */
  __X___XX,______XX,________,
  _XXX__XX,______XX,________,
  __XX__XX,_XXXXXXX,XXXXXX__,
  ___XX_XX,_XXXXXXX,XXXXXX__,
  ___X__XX,______XX,________,
  ____XXXX,______XX,________,
  __XXXXXX,______XX,________,
  _XXX__XX,__XXXXXX,XXXXX___,
  _X____XX,__XXXXXX,XXXXX___,
  ______XX,__XX____,________,
  ________,__XXX___,________,
  _XXXXXXX,XXXXXXXX,XXXXXX__,
  _XXXXXXX,XXXXXXXX,XXXXXX__,
  _______X,XX__XX__,__X_____,
  _____XXX,X____XX_,_XXXX___,
  ___XXXXX,_____XXX,XXXX____,
  XXXXX_XX,______XX,XXX_____,
  _XX___XX,___XX__X,XX______,
  ______XX,XXXXX___,_XX_____,
  ______XX,XXXX____,__XXX___,
  ______XX,X_______,____XX__};

GUI_CONST_STORAGE unsigned char acGUI_FontMicrosoftJhengHeiUI32_8D1F[ 69] = { /* code 8D1F */
  _______X,________,________,
  ______XX,X_______,________,
  _____XXX,XXXXXXXX,X_______,
  _____XXX,XXXXXXXX,X_______,
  ____XX__,_____XXX,________,
  ___XX___,_____XXX,________,
  __XX____,____XXX_,________,
  XXXXXXXX,XXXXXXXX,XXX_____,
  XX_XXXXX,XXXXXXXX,XXX_____,
  ___XX___,________,XXX_____,
  ___XX___,__XX____,XXX_____,
  ___XX___,__XX____,XXX_____,
  ___XX___,_XXX____,XXX_____,
  ___XX___,_XXX____,XXX_____,
  ___XX___,_XXX____,XXX_____,
  ___XX___,_XX_____,XXX_____,
  ___XX___,_XX_____,XXX_____,
  ___XX___,XXX_____,XXX_____,
  ________,XX__XX__,________,
  ______XX,XX__XXXX,X_______,
  ___XXXXX,X____XXX,XXXX____,
  XXXXXXX_,________,XXXXX___,
  XXXX____,________,___XX___};

GUI_CONST_STORAGE unsigned char acGUI_FontMicrosoftJhengHeiUI32_8F74[ 66] = { /* code 8F74 */
  __XX____,______XX,________,
  __XX____,______XX,________,
  __XX____,______XX,________,
  XXXXXXXX,X_____XX,________,
  XXXXXXXX,XXXXXXXX,XXXXX___,
  _XX_____,_XXXXXXX,XXXXX___,
  _XX_XX__,_XX___XX,___XX___,
  _XX_XX__,_XX___XX,___XX___,
  XXX_XX__,_XX___XX,___XX___,
  XX__XX__,_XX___XX,___XX___,
  XXXXXXXX,_XX___XX,___XX___,
  XXXXXXXX,_XXXXXXX,XXXXX___,
  ____XX__,_XXXXXXX,XXXXX___,
  ____XX__,_XX___XX,___XX___,
  ____XX__,_XX___XX,___XX___,
  ____XX_X,XXX___XX,___XX___,
  __XXXXXX,XXX___XX,___XX___,
  XXXXXXX_,_XX___XX,___XX___,
  XXX_XX__,_XX___XX,___XX___,
  ____XX__,_XXXXXXX,XXXXX___,
  ____XX__,_XXXXXXX,XXXXX___,
  ____XX__,_XX_____,___XX___};

GUI_CONST_STORAGE unsigned char acGUI_FontMicrosoftJhengHeiUI32_8F7D[ 69] = { /* code 8F7D */
  ______XX,______XX,________,
  ______XX,______XX,__X_____,
  ______XX,______XX,_XXX____,
  _XXXXXXX,XXXXX_XX,__XXX___,
  ______XX,______XX,___X____,
  ______XX,______XX,________,
  XXXXXXXX,XXXXXXXX,XXXXXX__,
  _____X__,______XX,________,
  ____XXX_,______XX,________,
  XXXXXXXX,XXXXX_XX,___X____,
  ___XX___,______XX,__XX____,
  __XXX_XX,______XX,__XX____,
  __XX__XX,______XX,XXXX____,
  _XX___XX,______XX,XXX_____,
  _XXXXXXX,XXXX___X,XXX_____,
  ______XX,_______X,XX______,
  ______XX,_______X,XX______,
  ______XX,___X__XX,XX__X___,
  ______XX,XXX___XX,XX__XX__,
  __XXXXXX,_____XX_,XX_XX___,
  XX____XX,____XXX_,_XXXX___,
  ______XX,__XXXX__,_XXXX___,
  ______XX,___XX___,__XX____};

GUI_CONST_STORAGE unsigned char acGUI_FontMicrosoftJhengHeiUI32_957F[ 63] = { /* code 957F */
  ____XX__,________,__XX____,
  ____XX__,________,XXX_____,
  ____XX__,______XX,X_______,
  ____XX__,____XXXX,________,
  ____XX__,_XXXXX__,________,
  ____XXXX,XXX_____,________,
  ____XXXX,X_______,________,
  ____XX__,________,________,
  XXXXXXXX,XXXXXXXX,XXXXX___,
  XXXXXXXX,XXXXXXXX,XXXXX___,
  ____XX__,__XX____,________,
  ____XX__,__XX____,________,
  ____XX__,___XX___,________,
  ____XX__,___XX___,________,
  ____XX__,____XX__,________,
  ____XX__,_____XX_,________,
  ____XX__,__X___XX,________,
  ____XX__,XXX____X,X_______,
  ____XXXX,XXX_____,XXX_____,
  ___XXXXX,X_______,__XX____,
  ____XX__,________,___XX___};

GUI_CONST_STORAGE GUI_CHARINFO_EXT GUI_FontMicrosoftJhengHeiUI32_CharInfo[14] = {
   {   1,   1,   0,  25,   6, acGUI_FontMicrosoftJhengHeiUI32_0020 } /* code 0020, SPACE */
  ,{  21,  21,   2,   5,  25, acGUI_FontMicrosoftJhengHeiUI32_4E0E } /* code 4E0E */
  ,{  20,  21,   3,   5,  25, acGUI_FontMicrosoftJhengHeiUI32_540C } /* code 540C */
  ,{  22,  23,   2,   4,  25, acGUI_FontMicrosoftJhengHeiUI32_5EA6 } /* code 5EA6 */
  ,{  23,  23,   1,   4,  25, acGUI_FontMicrosoftJhengHeiUI32_68C0 } /* code 68C0 */
  ,{  22,  23,   1,   4,  25, acGUI_FontMicrosoftJhengHeiUI32_6D4B } /* code 6D4B */
  ,{  21,  22,   3,   4,  25, acGUI_FontMicrosoftJhengHeiUI32_7535 } /* code 7535 */
  ,{  23,  22,   1,   4,  25, acGUI_FontMicrosoftJhengHeiUI32_7F06 } /* code 7F06 */
  ,{  22,  21,   2,   5,  25, acGUI_FontMicrosoftJhengHeiUI32_7F6E } /* code 7F6E */
  ,{  23,  21,   1,   5,  25, acGUI_FontMicrosoftJhengHeiUI32_88C5 } /* code 88C5 */
  ,{  22,  23,   2,   4,  25, acGUI_FontMicrosoftJhengHeiUI32_8D1F } /* code 8D1F */
  ,{  21,  22,   2,   4,  25, acGUI_FontMicrosoftJhengHeiUI32_8F74 } /* code 8F74 */
  ,{  22,  23,   2,   4,  25, acGUI_FontMicrosoftJhengHeiUI32_8F7D } /* code 8F7D */
  ,{  22,  21,   2,   5,  25, acGUI_FontMicrosoftJhengHeiUI32_957F } /* code 957F */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontMicrosoftJhengHeiUI32_Prop14 = {
   0x957F /* first character */
  ,0x957F /* last character  */
  ,&GUI_FontMicrosoftJhengHeiUI32_CharInfo[ 13] /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP_EXT *)0 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontMicrosoftJhengHeiUI32_Prop13 = {
   0x8F7D /* first character */
  ,0x8F7D /* last character  */
  ,&GUI_FontMicrosoftJhengHeiUI32_CharInfo[ 12] /* address of first character */
  ,&GUI_FontMicrosoftJhengHeiUI32_Prop14 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontMicrosoftJhengHeiUI32_Prop12 = {
   0x8F74 /* first character */
  ,0x8F74 /* last character  */
  ,&GUI_FontMicrosoftJhengHeiUI32_CharInfo[ 11] /* address of first character */
  ,&GUI_FontMicrosoftJhengHeiUI32_Prop13 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontMicrosoftJhengHeiUI32_Prop11 = {
   0x8D1F /* first character */
  ,0x8D1F /* last character  */
  ,&GUI_FontMicrosoftJhengHeiUI32_CharInfo[ 10] /* address of first character */
  ,&GUI_FontMicrosoftJhengHeiUI32_Prop12 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontMicrosoftJhengHeiUI32_Prop10 = {
   0x88C5 /* first character */
  ,0x88C5 /* last character  */
  ,&GUI_FontMicrosoftJhengHeiUI32_CharInfo[  9] /* address of first character */
  ,&GUI_FontMicrosoftJhengHeiUI32_Prop11 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontMicrosoftJhengHeiUI32_Prop9 = {
   0x7F6E /* first character */
  ,0x7F6E /* last character  */
  ,&GUI_FontMicrosoftJhengHeiUI32_CharInfo[  8] /* address of first character */
  ,&GUI_FontMicrosoftJhengHeiUI32_Prop10 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontMicrosoftJhengHeiUI32_Prop8 = {
   0x7F06 /* first character */
  ,0x7F06 /* last character  */
  ,&GUI_FontMicrosoftJhengHeiUI32_CharInfo[  7] /* address of first character */
  ,&GUI_FontMicrosoftJhengHeiUI32_Prop9 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontMicrosoftJhengHeiUI32_Prop7 = {
   0x7535 /* first character */
  ,0x7535 /* last character  */
  ,&GUI_FontMicrosoftJhengHeiUI32_CharInfo[  6] /* address of first character */
  ,&GUI_FontMicrosoftJhengHeiUI32_Prop8 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontMicrosoftJhengHeiUI32_Prop6 = {
   0x6D4B /* first character */
  ,0x6D4B /* last character  */
  ,&GUI_FontMicrosoftJhengHeiUI32_CharInfo[  5] /* address of first character */
  ,&GUI_FontMicrosoftJhengHeiUI32_Prop7 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontMicrosoftJhengHeiUI32_Prop5 = {
   0x68C0 /* first character */
  ,0x68C0 /* last character  */
  ,&GUI_FontMicrosoftJhengHeiUI32_CharInfo[  4] /* address of first character */
  ,&GUI_FontMicrosoftJhengHeiUI32_Prop6 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontMicrosoftJhengHeiUI32_Prop4 = {
   0x5EA6 /* first character */
  ,0x5EA6 /* last character  */
  ,&GUI_FontMicrosoftJhengHeiUI32_CharInfo[  3] /* address of first character */
  ,&GUI_FontMicrosoftJhengHeiUI32_Prop5 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontMicrosoftJhengHeiUI32_Prop3 = {
   0x540C /* first character */
  ,0x540C /* last character  */
  ,&GUI_FontMicrosoftJhengHeiUI32_CharInfo[  2] /* address of first character */
  ,&GUI_FontMicrosoftJhengHeiUI32_Prop4 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontMicrosoftJhengHeiUI32_Prop2 = {
   0x4E0E /* first character */
  ,0x4E0E /* last character  */
  ,&GUI_FontMicrosoftJhengHeiUI32_CharInfo[  1] /* address of first character */
  ,&GUI_FontMicrosoftJhengHeiUI32_Prop3 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontMicrosoftJhengHeiUI32_Prop1 = {
   0x0020 /* first character */
  ,0x0020 /* last character  */
  ,&GUI_FontMicrosoftJhengHeiUI32_CharInfo[  0] /* address of first character */
  ,&GUI_FontMicrosoftJhengHeiUI32_Prop2 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT GUI_FontMicrosoftJhengHeiUI32 = {
   GUI_FONTTYPE_PROP_EXT /* type of font    */
  ,32 /* height of font  */
  ,32 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,{&GUI_FontMicrosoftJhengHeiUI32_Prop1}
  ,25 /* Baseline */
  ,14 /* Height of lowercase characters */
  ,19 /* Height of capital characters */
};

